fun_facts = [
    "The yellow umbrella that appears throughout the series was actually a last-minute prop choice, as the original blue umbrella didn't show up well on camera.",
    "The show's creators, Carter Bays and Craig Thomas, based the character of Ted on themselves and their experiences in New York City.",
    "The apartment numbers in the show (4A and 4B) are a reference to the Beatles' song 'When I'm 64'.",
    "The show's theme song, 'Hey Beautiful' by The Solids, is performed by the show's creators' band.",
    "The character of Barney Stinson was originally supposed to be a one-time character, but Neil Patrick Harris's performance made him a series regular.",
    "The show's famous 'Slap Bet' was actually improvised by Neil Patrick Harris and Jason Segel.",
    "The blue French horn that Ted steals for Robin is the same prop used in every episode where it appears.",
    "The show's creators had the ending planned from the very beginning of the series.",
    "The character of the Mother was kept a secret for the entire series, with only the creators and the actress knowing her identity.",
    "The show's famous 'Bro Code' was actually published as a real book in 2008.",
    "Cobie Smulders (Robin) is actually Canadian, just like her character.",
    "The show's creators appear as extras in several episodes.",
    "Barney's job is a running joke: 'Please.'",
    "The pineapple incident is never fully explained in the show, but was revealed in a deleted scene.",
    "Marshall's favorite beer is Heisler, a fictional brand used in many TV shows.",
    "The cast had to film the kids' ending scenes in the first season to avoid them aging.",
    "The blue French horn became a real-life symbol for fans of the show.",
    "Alyson Hannigan (Lily) is allergic to dogs, so Robin's dogs were written out after season 2.",
    "The bar, MacLaren's, is named after one of the show's producers.",
    "The cast would often hang out together off set, just like their characters."
]

jokes = [
    "Why did Barney get kicked out of the bar? He was caught doing the 'Suit Up' dance without a suit!",
    "What did Ted say when he lost his architecture job? 'I guess I'll have to draw the line somewhere else!'",
    "Why did Marshall become a judge? Because he couldn't handle being a law-yer!",
    "What did Robin say when she lost her job at World Wide News? 'I guess I'm not so world-wide anymore!'",
    "Why did Lily become a kindergarten teacher? Because she couldn't handle being a paint-er!",
    "What did Barney say when he got his first suit? 'It's going to be legen... wait for it... dary!'",
    "Why did Ted's blue French horn get stolen? Because it was too horn-y!",
    "What did Marshall say when he lost his bet with Barney? 'I guess I'm not so suit-ed for this!'",
    "Why did Robin move to New York? Because she couldn't handle being a Canuck!",
    "What did Lily say when she got her first art show? 'It's going to be paint-astic!'",
    "Why did Barney always go to MacLaren's? Because that's where the legen—wait for it—dary nights happen!",
    "Why did Ted bring a pineapple to bed? Because he wanted a sweet dream!",
    "Why did Marshall eat so many burgers? He was on a bun-quest!",
    "Why did Robin always have a gun? Because she was always on the hunt for a good story!",
    "Why did Lily hide the goat? Because she didn't want to get baaa-d grades!",
    "Why did Ted become an architect? Because he wanted to build relationships!",
    "Why did Barney always wear a suit? Because he wanted to look 'suit-able' for every occasion!",
    "Why did Lily become a teacher? Because she wanted to school everyone in love!",
    "Why did Robin become a news anchor? Because she wanted to make headlines!",
    "Why did Marshall love Minnesota? Because it was 'legen-dairy'!",
    "Why did Ted steal the blue French horn? Because he wanted to play the tune of love!",
    "Why did Barney invent the Bro Code? To keep his legendary status!",
    "Why did Lily hide the goat? Because it was a baaa-d influence!",
    "Why did Robin love guns? Because she was always on target!",
    "Why did Marshall eat so many burgers? He was on a bun-quest!",
    "Why did Ted always tell stories? Because he wanted to be a legen-dary dad!",
    "Why did Barney love magic? Because he liked to make girls disappear!",
    "Why did Robin sing 'Let's Go to the Mall'? Because she wanted to shop for love!",
    "Why did Marshall become a judge? Because he wanted to lay down the law of love!",
    "Why did Lily love art? Because she wanted to draw people together!"
]

interesting_quotes = [
    "When I'm sad, I stop being sad and be awesome instead. - Barney Stinson",
    "Nothing good happens after 2 A.M. - Ted Mosby",
    "The future is scary, but you can't just run back to the past because it's familiar. - Robin Scherbatsky",
    "You can't design your life like a building. It doesn't work that way. You just have to live it, and it will design itself. - Ted Mosby",
    "The only reason to wait a month for sex is if you're seventeen and hoping to lose your virginity in the back of a Camry. - Barney Stinson",
    "Love is the best thing we do. - Ted Mosby",
    "Whatever you do in this life, it's not legendary unless your friends are there to see it. - Barney Stinson",
    "You can't cling to the past, because no matter how tightly you hold on, it's already gone. - Ted Mosby",
    "The truth is, you can't be sure of anything. You just have to do your best and take a lot of naps. - Marshall Eriksen",
    "Sometimes things have to fall apart to make way for better things. - Ted Mosby",
    "Sometimes even if you know how something's gonna end, that doesn't mean you can't enjoy the ride. - Ted Mosby",
    "If you're not scared, you're not taking a chance. And if you're not taking a chance, then what the hell are you doing? - Ted Mosby",
    "Whatever you do in this life, it's not legendary unless your friends are there to see it. - Barney Stinson",
    "You can't just skip ahead to where you think your life should be. - Lily Aldrin",
    "The best thing you can do is to fake confidence until it's real. - Barney Stinson",
    "We struggle so hard to hold on to these things that we know are gonna disappear eventually. And that's really noble. - Lily Aldrin",
    "Because sometimes even if you know how something's gonna end, that doesn't mean you can't enjoy the ride. - Ted Mosby",
    "I realized that I'm searching, searching for what I really want in life. - Robin Scherbatsky",
    "You can't cling to the past, because no matter how tightly you hold on, it's already gone. - Ted Mosby",
    "The future is scary, but you can't just run back to the past because it's familiar. - Robin Scherbatsky"
]

pickup_lines = [
    "Haaaaave you met Ted?",
    "You know what my friends call me? The Barnacle. Because I always stick around.",
    "I'm not a photographer, but I can picture us together.",
    "Is your name Google? Because you have everything I've been searching for.",
    "I'm Barney. You're awesome. Let's be awesome together.",
    "I'm sorry, I don't think we've met. I wouldn't forget a smile like that.",
    "Do you believe in love at first sight, or should I walk by again?",
    "I'm going to buy you a drink. And then, I'm going to take you home.",
    "I'm not trying to impress you, but I'm Batman.",
    "I'm not a big drinker, but I'd love to buy you a drink and get to know you.",
    "I'm not a gambler, but I've just bet my heart on you.",
    "I'm not a weatherman, but you can expect a few inches tonight.",
    "I'm not a genie, but I can make your dreams come true.",
    "I'm not a doctor, but this might hurt a little.",
    "I'm not a dentist, but I could give you a filling.",
    "I'm not a firefighter, but I can make your heart race.",
    "I'm not a pilot, but I can take you to new heights.",
    "I'm not a magician, but I can make your clothes disappear.",
    "I'm not a lawyer, but I can give you a legal reason to smile.",
    "I'm not a chef, but I can spice up your life.",
    "Are you a Slap Bet Commissioner? Because my heart skips a beat every time I see you!",
    "Is your name Robin? Because you just stole my heart, Scherbatsky!",
    "Are you a yellow umbrella? Because I've been waiting for you forever.",
    "Do you believe in destiny? Because I think we met at MacLaren's for a reason.",
    "Are you a blue French horn? Because I'd go the extra mile for you.",
    "Are you a goat? Because you're the greatest of all time!",
    "Are you a Canadian pop star? Because you rock my world, Robin Sparkles!",
    "Are you a pineapple? Because you're a mystery I want to solve.",
    "Are you a Bro Code? Because I want to follow your rules.",
    "Are you a legendary night? Because I'll never forget you!"
] 